//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NAV.RC
//
#define IDC_AIRCRAFT                    2
#define IDC_WIND                        3
#define ID_SENDTOPLAN                   3
#define IDC_FILE                        4
#define IDC_FLYTOPLAN                   5
#define IDC_FLYTOPLANBUTTON             5
#define IDC_DPSTAR                      6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_NAVTYPE                     129
#define IDD_TITLE                       130
#define IDD_DATABASE                    131
#define IDD_SEARCH                      132
#define IDD_FLIGHTPLAN                  133
#define IDD_DETAILS                     134
#define IDD_AUTO                        135
#define IDD_SEARCHBGL                   136
#define IDI_ICON1                       137
#define IDD_EXPORT                      138
#define IDD_EXPORTPROGRESS              139
#define IDD_DENSITY                     140
#define IDD_SETTRANSITION               141
#define IDD_NEWLIST                     143
#define IDD_CENTERAT                    144
#define IDD_CRAFT                       145
#define IDD_LOADAIRCRAFT                146
#define IDR_NAVPLAN                     147
#define IDD_WIND                        148
#define IDD_LINKOPTIONS                 149
#define IDR_PLANMENU                    150
#define IDD_MAPOPTIONS                  151
#define IDD_SETMAPOPTIONS               152
#define IDD_INSERT_A_GPS_FIX            153
#define IDB_FLIGHTPLANIMAGELIST         154
#define IDD_CREATEDPSTAR                155
#define IDD_SELECTDPSTAR                156
#define IDD_INSERTGPSFIX                157
#define IDC_TITLE                       1000
#define IDC_LIST                        1002
#define IDC_CENTER                      1003
#define IDC_DETAILS                     1004
#define IDC_TARGET                      1005
#define IDC_SUMMARY                     1005
#define IDC_UP                          1007
#define IDC_DOWN                        1008
#define IDC_DELETE                      1009
#define IDC_ADD                         1010
#define IDC_PRINT                       1011
#define IDC_PLAN                        1012
#define IDC_TEXT                        1013
#define IDC_AUTO                        1014
#define IDC_OPTIONS                     1015
#define IDC_CLEAR                       1016
#define IDC_VOR                         1017
#define IDC_NDB                         1018
#define IDC_AIRPORTS                    1019
#define IDC_IDEAL                       1020
#define IDC_CONTINUE                    1021
#define IDC_DRIVE                       1022
#define IDC_WAYPOINTS                   1022
#define IDC_CHECK1                      1023
#define IDC_CHECK2                      1024
#define IDC_STATE                       1025
#define IDC_CHECK3                      1025
#define IDC_HEADINGS                    1028
#define IDC_NAVAIDS                     1029
#define IDC_RUNWAYS                     1030
#define IDC_DENSITY                     1031
#define IDC_TRANS                       1032
#define IDC_NAME                        1034
#define IDC_ID                          1035
#define IDC_LATD                        1036
#define IDC_LATM                        1037
#define IDC_LATS                        1038
#define IDC_DDEGLAT                     1039
#define IDC_LOND                        1040
#define IDC_LONM                        1041
#define IDC_LONS                        1042
#define IDC_DDEGLON                     1043
#define IDC_RADIODD                     1044
#define IDC_RADIODMSD                   1045
#define IDC_CRAFT                       1046
#define IDC_DS                          1047
#define IDC_CS                          1048
#define IDC_US                          1049
#define IDC_DF                          1050
#define IDC_CF                          1051
#define IDC_UF                          1052
#define IDC_DR                          1053
#define IDC_LOAD                        1054
#define IDC_UR                          1055
#define IDC_CA                          1057
#define IDC_SAVEAS                      1059
#define IDC_SAVE                        1059
#define IDC_SPEED                       1061
#define IDC_DIRECTION                   1062
#define IDC_GLOBAL                      1063
#define IDC_UPDATE                      1064
#define IDC_FLYUPDATE                   1065
#define IDC_SETNAVMODE                  1066
#define IDC_ZOOM                        1067
#define IDC_ENABLENETWORK               1067
#define IDC_CENTERLAT                   1068
#define IDC_CALLSIGN                    1068
#define IDC_CENTERLON                   1069
#define IDC_FLATMAP                     1070
#define IDC_DECIMATION                  1071
#define IDC_RED                         1072
#define IDC_MAG                         1073
#define IDC_SHOWALL                     1074
#define IDC_GREEN                       1075
#define IDC_BLUE                        1076
#define IDC_CHANGE                      1077
#define IDC_IPB1                        1078
#define IDC_IPB2                        1079
#define IDC_IPB3                        1080
#define IDC_NPB1                        1081
#define IDC_NPB2                        1082
#define IDC_NPB3                        1083
#define IDC_CIL1                        1084
#define IDC_CIL2                        1085
#define IDC_CIL3                        1086
#define IDC_CIL4                        1087
#define IDC_CIL6                        1088
#define IDC_CIL7                        1089
#define IDC_CIL8                        1090
#define IDC_CIL9                        1091
#define IDC_CIL10                       1092
#define IDC_CIL13                       1093
#define IDC_CIL14                       1094
#define IDC_CIL15                       1095
#define IDC_RIV1                        1096
#define IDC_RIV2                        1097
#define IDC_RIV3                        1098
#define IDC_RIV4                        1099
#define IDC_RIV5                        1100
#define IDC_RIV6                        1101
#define IDC_RIV7                        1102
#define IDC_RIV8                        1103
#define IDC_RIV10                       1104
#define IDC_RIV11                       1105
#define IDC_RIV12                       1106
#define IDC_INSERT_GPSFIX_HDG           1107
#define IDC_SPIN_HEADING                1108
#define IDC_INSERT_GPSFIX_DISTANCE      1109
#define IDC_SPIN_DISTANCE               1110
#define IDC_GPSFIX_INSERT               1111
#define IDC_GPSFIX_NEWLAT               1112
#define IDC_GPSFIX_NEWLONG              1113
#define IDC_HEADING_REVERSE             1114
#define IDC_CHOOSE                      1115
#define IDC_TIMESTAMP                   1116
#define IDC_PROMPT                      1118
#define IDC_ROUTENAME                   1119
#define ID_VIEW_ZOOMIN                  32771
#define ID_VIEW_ZOOMOUT                 32772
#define ID_VIEW_GRIDLINES               32773
#define ID_FILE_ADDTOSCENERYLIST        32774
#define ID_FILE_LOADSCENERYLIST         32775
#define ID_FILE_SEARCHFORFILESTOADDTOSCENERYLIST 32776
#define ID_FILE_ADD                     32777
#define ID_FILE_SEARCH                  32778
#define ID_FILE_LOAD                    32779
#define ID_VIEW_VOR                     32780
#define ID_VIEW_ILS                     32781
#define ID_VIEW_NDB                     32782
#define ID_VIEW_AIRPORTS                32783
#define ID_VIEW_NAVAIDID                32784
#define ID_VIEW_NAVAIDFREQUENCY         32785
#define ID_VIEW_FREQUENCY               32786
#define ID_VIEW_ID                      32787
#define ID_EDIT_CHANGEFONT              32788
#define ID_EDIT_SETTITLE                32789
#define ID_VIEW_DETAILS                 32790
#define ID_VIEW_SEARCH                  32791
#define ID_VIEW_DATABASE                32792
#define ID_EDIT_SAVEOPTIONS             32793
#define ID_VIEW_FLATWORLD               32794
#define ID_HELP_TEST                    32795
#define ID_EDIT_FLIGHTPLAN              32796
#define ID_PLAN_PLANOPTIONS             32798
#define ID_MAP_SHOW_PLANDATAONLY        32799
#define ID_VIEW_MARKERS                 32800
#define ID_MAP_SHOW_PLANINFORMATION     32801
#define ID_FILE_EXPORT                  32803
#define ID_FILE_IMPORT                  32804
#define ID_MAP_FLIGHTTRACK_CLEARFLIGHTTRACK 32805
#define ID_MAP_CLEARFLIGHTTRACK         32806
#define ID_MAP_FLIGHTTRACK_SETFLIGHTTRACKDENSITY 32807
#define ID_MAP_SETFLIGHTTRACKDENSITY    32808
#define ID_MAP_LARGESYMBOLS             32809
#define ID_MAP_SHOW_MAPSYMBOLS_SETTRANSITION 32810
#define ID_MAP_SETTRANSITION            32811
#define ID_MAP_ZOOMTOFIT                32812
#define ID_MAP_SHOW_MAPS                32813
#define ID_MAP_SHOW_MAPSYMBOLS_AIRPORTZONES 32814
#define ID_MAP_INSERTGPSFIX             32815
#define ID_FILE_LOADSCENERYLIST_NAVLST  32816
#define ID_FILE_ADDTOSCENERYLIST_NEW    32817
#define ID_FILE_ADDTOSCENERYLIST_NAVLST 32818
#define ID_FILE_SEARCHFORBGLFILES_NEW   32819
#define ID_FILE_SEARCHFORBGLFILES_NAVLST 32820
#define ID_MAP_CENTERAT                 32821
#define ID_MAP_SHOW_ATIS                32822
#define ID_MAP_ATIS                     32823
#define ID_FS6_LINK                     32824
#define ID_FS6_SET                      32825
#define ID_FS6_FS6LINKOPTIONS           32826
#define ID_EDIT_MOVEUP                  32831
#define ID_EDIT_MOVEDOWN                32832
#define ID_EDIT_DELETE                  32833
#define ID_EDIT_CLEARALL                32834
#define ID_EDIT_ADD                     32835
#define ID_EDIT_AUTOROUTE               32836
#define ID_EDIT_WIND                    32837
#define ID_AIRCRAFT                     32838
#define ID_OPTIONS                      32839
#define ID_FS6_FLYTO                    32840
#define ID_MENUITEM32841                32841
#define ID_HELPVIEWDOCS                 32842
#define ID_FILE_EXPORTSQUAWKBOX         32843
#define ID_MENUITEM32844                32844
#define ID_VIEW_WAYPOINTS               32845
#define ID_VIEW_ROUTES                  32846
#define ID_MENUITEM32847                32847
#define ID_MAP_SHOW_FANCYMAPS           32848
#define ID_SET_FANCYMAP_OPTIONS         32849
#define ID_FS6_FLYTO_PLAN               32851
#define ID_PLAN0                        32852
#define ID_INCREMENTFLYTOWAYPOINT       32853
#define ID_FILE_SAVECOMPILEDSCENERYLIST 32854
#define ID_FILE_DELETECOMPILEDSCENERYLIST 32855
#define ID_FILE_EXPORTSUPERFLIGHTPLANNER 32856
#define ID_FILE_EXPORT_FLIGHTSHOP       32857
#define ID_FILE_EXPORTTORADARCONTACT99  32858
#define ID_FILE_IMPORT_IMPORTFROMSUPERFLIGHTPLANNER 32859
#define ID_FILE_IMPORTFROMOLDNAV1X      32860
#define ID_FILE_STARTWITHLASTLIST       32861
#define ID_FILE_EXPORT_EXPORTTOACSGPS   32862
#define ID_FILE_EXPORT_ACSGPS           32863
#define ID_INITIATELINKDRAWING          32864
#define ID_FILE_EXPORTTOFLIGHTSIMULATOR2000 32865
#define ID_FILE_IMPORTFROMFLIGHTSIMULATOR2000 32866
#define ID_FILE_EXTRACTFS2000WAYPOINTSANDROUTES 32867
#define ID_MAP_STARTWITHLASTVIEW        32868
#define ID_FLIGHTSIM_MAPFOLLOWSAIRCRAFT_NONE 32869
#define ID_FLIGHTSIM_MAPFOLLOWSAIRCRAFT_LOCAL 32870
#define ID_FILE_SAVEASDPSTAR            32872

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
